
from bot.locals import Local

LOCAL = Local({
    'WRONG_ROOM' : 'masukkan password bot /pass 123 \nID : <code>{CHAT_ID}</code>',
    'WELCOME_MESSAGE' : "Hi!",
    'PASS_REQUIRED' : '\n\nUse <code>/{cmd_pass} </code>masukan password bot ini!.',
    'LEECH_LIST_MESSAGE_HEADER' : '<b>Leech Status</b>',
    'LEECH_LIST_FORMAT' : 'Name: <code>{name}</code>\nStatus: {status}\nID: <code>{gid}</code>\n\n',
    'ARIA2_CHECKING_LINK' : "Checking...",
    'ARIA2_DOWNLOAD_STATUS' : "Sedang mendownload : <code>{name}</code>\n{block} {percentage}\nSize : {total_size}\nDN : {download_speed} / UP : {upload_speed}\nSeeder : {seeder}\nETA : {eta}\nID : <code>{gid}</code>",
    'ARIA2_DOWNLOAD_SUCCESS' : 'File terunduh : <code>{name}</code>',
    'ARIA2_DOWNLOAD_CANCELED' : 'Download dibatalkan : <code>{name}</code>',
    'ARIA2_DEAD_LINK' : 'Download dibatalkan otomatis : <code>{name}</code>\nYour Torrent/Link is Dead.',
    'ARIA2_NO_URI' : 'Link rusak.',
    'UPLOADING_FILE' : 'Uploading : <code>{name}</code>',
    'UPLOADING_PROGRESS' : 'Uploading : <code>{name}</code>\n{block} {percentage}%\nSize : {size}\nUP : {upload_speed}/s\nETA : {eta}',
    'UPLOAD_FAILED_FILE_MISSING' : 'Upload : Gagal. file tidak ada.\n<code>{name}</code>',
    'GENERATE_THUMBNAIL' : 'Thumbnail : Generating.\n<code>{name}</code>',
    'SPLIT_FILE' : 'Membagi File : <code>{name}</code>',
    'SPLIT_FAILED' : 'Membagi : Gagal.\n<code>{name}</code>',
    'THUMBNAIL_NO_PHOTO' : 'gunakan <code>/{cmd_set_thumbnail}</code> didalam caption foto.',
    'THUMBNAIL_DOWNLOADING' : 'mengunduh thumbnail.',
    'THUMBNAIL_DOWNLOADED' : 'Thumbnail terunduh.',
    'THUMBNAIL_APPLIED' : 'Thumbnail dipakai.',
    'THUMBNAIL_DELETING' : 'menghapus thumbnail.',
    'THUMBNAIL_RESET' : 'Thumbnail diatur ulang.',
    'UPLOAD_AS_DOC' : 'Unggah sebagai dokumen yang disetel ke‌‌ {status}.',
    'UPLOAD_AS_ZIP' : 'Unggah sebagai file zip yang disetel ke‌‌ {status}.',
    'TRACKER_RESET' : 'Default torrent tracker reset.',
    'TRACKER_APPLIED' : 'Default torrent tracker applied.',
    'HELP_MESSAGE_HEADER' : '<b>Bot Command</b>',
    'NO_HELP_INFO' : 'no information',
    'COMMAND_START' : 'start bot',
    'COMMAND_PASSWORD' : 'masukan pasword bot ini',
    'COMMAND_HELP' : 'this message',
    'COMMAND_LEECH' : 'leech link or magnet',
    'COMMAND_CANCEL_LEECH' : 'cancel leeching',
    'COMMAND_LEECH_LIST' : 'list on going leech',
    'COMMAND_SET_THUMBNAIL' : 'set custom video thumbail',
    'COMMAND_RESET_THUMBNAIL' : 'reset custom video thumbnail',
    'COMMAND_UPLOAD_AS_DOC' : 'toggle upload anything as document',
    'COMMAND_UPLOAD_AS_ZIP' : 'toggle upload anything as bundled zipfile',
    'COMMAND_SET_TRACKER' : 'set default tracker, sparated by newline',
    'BLOCK_EMPTY' : "▱",
    "BLOCK_FILLED" : "▰"
})
